//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace Nevolution.Core.Resources;

using System.Globalization;
using System.Resources;

public class Strings
{
    private static ResourceManager? resourceMan;
    private static CultureInfo? resourceCulture;

    public Strings()
    {
    }

    public static ResourceManager ResourceManager => resourceMan ??= new ResourceManager("Nevolution.Core.Resources.Strings", typeof(Strings).Assembly);

    public static CultureInfo? Culture
    {
        get => resourceCulture;
        set => resourceCulture = value;
    }

    public static string Folder_Archive => ResourceManager.GetString(nameof(Folder_Archive), resourceCulture) ?? nameof(Folder_Archive);
    public static string Folder_Drafts => ResourceManager.GetString(nameof(Folder_Drafts), resourceCulture) ?? nameof(Folder_Drafts);
    public static string Folder_Inbox => ResourceManager.GetString(nameof(Folder_Inbox), resourceCulture) ?? nameof(Folder_Inbox);
    public static string Folder_Sent => ResourceManager.GetString(nameof(Folder_Sent), resourceCulture) ?? nameof(Folder_Sent);
    public static string Folder_Trash => ResourceManager.GetString(nameof(Folder_Trash), resourceCulture) ?? nameof(Folder_Trash);
    public static string Cli_AccountNotFound => ResourceManager.GetString(nameof(Cli_AccountNotFound), resourceCulture) ?? nameof(Cli_AccountNotFound);
    public static string Cli_AccountSaved => ResourceManager.GetString(nameof(Cli_AccountSaved), resourceCulture) ?? nameof(Cli_AccountSaved);
    public static string Cli_ActiveAccount => ResourceManager.GetString(nameof(Cli_ActiveAccount), resourceCulture) ?? nameof(Cli_ActiveAccount);
    public static string Cli_AuthenticationFailed => ResourceManager.GetString(nameof(Cli_AuthenticationFailed), resourceCulture) ?? nameof(Cli_AuthenticationFailed);
    public static string Cli_ConnectionFailed => ResourceManager.GetString(nameof(Cli_ConnectionFailed), resourceCulture) ?? nameof(Cli_ConnectionFailed);
    public static string Cli_DetailPrefix => ResourceManager.GetString(nameof(Cli_DetailPrefix), resourceCulture) ?? nameof(Cli_DetailPrefix);
    public static string Cli_ErrorPrefix => ResourceManager.GetString(nameof(Cli_ErrorPrefix), resourceCulture) ?? nameof(Cli_ErrorPrefix);
    public static string Cli_HostResolutionFailed => ResourceManager.GetString(nameof(Cli_HostResolutionFailed), resourceCulture) ?? nameof(Cli_HostResolutionFailed);
    public static string Cli_NoAccountsConfigured => ResourceManager.GetString(nameof(Cli_NoAccountsConfigured), resourceCulture) ?? nameof(Cli_NoAccountsConfigured);
    public static string Cli_NoActiveAccount => ResourceManager.GetString(nameof(Cli_NoActiveAccount), resourceCulture) ?? nameof(Cli_NoActiveAccount);
    public static string Cli_RequiredArgumentMissing => ResourceManager.GetString(nameof(Cli_RequiredArgumentMissing), resourceCulture) ?? nameof(Cli_RequiredArgumentMissing);
    public static string Cli_ResolvingHost => ResourceManager.GetString(nameof(Cli_ResolvingHost), resourceCulture) ?? nameof(Cli_ResolvingHost);
    public static string Cli_SyncedEmailsCount => ResourceManager.GetString(nameof(Cli_SyncedEmailsCount), resourceCulture) ?? nameof(Cli_SyncedEmailsCount);
    public static string Cli_SyncingFolder => ResourceManager.GetString(nameof(Cli_SyncingFolder), resourceCulture) ?? nameof(Cli_SyncingFolder);
    public static string Cli_UnknownAccountCommand => ResourceManager.GetString(nameof(Cli_UnknownAccountCommand), resourceCulture) ?? nameof(Cli_UnknownAccountCommand);
    public static string Cli_UsageAccountAdd => ResourceManager.GetString(nameof(Cli_UsageAccountAdd), resourceCulture) ?? nameof(Cli_UsageAccountAdd);
    public static string Cli_UsageAccountList => ResourceManager.GetString(nameof(Cli_UsageAccountList), resourceCulture) ?? nameof(Cli_UsageAccountList);
    public static string Cli_UsageAccountUse => ResourceManager.GetString(nameof(Cli_UsageAccountUse), resourceCulture) ?? nameof(Cli_UsageAccountUse);
    public static string Cli_UsageHeader => ResourceManager.GetString(nameof(Cli_UsageHeader), resourceCulture) ?? nameof(Cli_UsageHeader);
    public static string Language_English => ResourceManager.GetString(nameof(Language_English), resourceCulture) ?? nameof(Language_English);
    public static string Language_Spanish => ResourceManager.GetString(nameof(Language_Spanish), resourceCulture) ?? nameof(Language_Spanish);
    public static string MainWindow_FilterPlaceholder => ResourceManager.GetString(nameof(MainWindow_FilterPlaceholder), resourceCulture) ?? nameof(MainWindow_FilterPlaceholder);
    public static string MainWindow_HtmlFallbackNotice => ResourceManager.GetString(nameof(MainWindow_HtmlFallbackNotice), resourceCulture) ?? nameof(MainWindow_HtmlFallbackNotice);
    public static string MainWindow_LanguageLabel => ResourceManager.GetString(nameof(MainWindow_LanguageLabel), resourceCulture) ?? nameof(MainWindow_LanguageLabel);
    public static string MainWindow_LoadMore => ResourceManager.GetString(nameof(MainWindow_LoadMore), resourceCulture) ?? nameof(MainWindow_LoadMore);
    public static string MainWindow_ShowUnreadOnly => ResourceManager.GetString(nameof(MainWindow_ShowUnreadOnly), resourceCulture) ?? nameof(MainWindow_ShowUnreadOnly);
    public static string MainWindow_Title => ResourceManager.GetString(nameof(MainWindow_Title), resourceCulture) ?? nameof(MainWindow_Title);
    public static string MailBody_Loading => ResourceManager.GetString(nameof(MailBody_Loading), resourceCulture) ?? nameof(MailBody_Loading);
    public static string Status_BackgroundDownloadStopped => ResourceManager.GetString(nameof(Status_BackgroundDownloadStopped), resourceCulture) ?? nameof(Status_BackgroundDownloadStopped);
    public static string Status_CannotDownloadSelectedMailBody => ResourceManager.GetString(nameof(Status_CannotDownloadSelectedMailBody), resourceCulture) ?? nameof(Status_CannotDownloadSelectedMailBody);
    public static string Status_CannotLoadActiveAccount => ResourceManager.GetString(nameof(Status_CannotLoadActiveAccount), resourceCulture) ?? nameof(Status_CannotLoadActiveAccount);
    public static string Status_CannotSyncActiveFolder => ResourceManager.GetString(nameof(Status_CannotSyncActiveFolder), resourceCulture) ?? nameof(Status_CannotSyncActiveFolder);
    public static string Status_InitialLoadFailed => ResourceManager.GetString(nameof(Status_InitialLoadFailed), resourceCulture) ?? nameof(Status_InitialLoadFailed);
    public static string Status_InitialLoadFailedImap => ResourceManager.GetString(nameof(Status_InitialLoadFailedImap), resourceCulture) ?? nameof(Status_InitialLoadFailedImap);
    public static string Status_NoLocalEmailsYet => ResourceManager.GetString(nameof(Status_NoLocalEmailsYet), resourceCulture) ?? nameof(Status_NoLocalEmailsYet);
    public static string Status_NoActiveAccount => ResourceManager.GetString(nameof(Status_NoActiveAccount), resourceCulture) ?? nameof(Status_NoActiveAccount);
    public static string Status_SyncingFolder => ResourceManager.GetString(nameof(Status_SyncingFolder), resourceCulture) ?? nameof(Status_SyncingFolder);
    public static string UserError_ImapAuthentication => ResourceManager.GetString(nameof(UserError_ImapAuthentication), resourceCulture) ?? nameof(UserError_ImapAuthentication);
    public static string UserError_ImapConnection => ResourceManager.GetString(nameof(UserError_ImapConnection), resourceCulture) ?? nameof(UserError_ImapConnection);
    public static string UserError_ImapGeneric => ResourceManager.GetString(nameof(UserError_ImapGeneric), resourceCulture) ?? nameof(UserError_ImapGeneric);
    public static string UserError_ImapHostResolution => ResourceManager.GetString(nameof(UserError_ImapHostResolution), resourceCulture) ?? nameof(UserError_ImapHostResolution);
    public static string UserError_ImapInvalidAccountConfiguration => ResourceManager.GetString(nameof(UserError_ImapInvalidAccountConfiguration), resourceCulture) ?? nameof(UserError_ImapInvalidAccountConfiguration);
    public static string UserError_ImapSecurity => ResourceManager.GetString(nameof(UserError_ImapSecurity), resourceCulture) ?? nameof(UserError_ImapSecurity);
}
