//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace Nevolution.Core.Resources;

using System.Globalization;
using System.Resources;

public class Strings
{
    private static ResourceManager? resourceMan;
    private static CultureInfo? resourceCulture;

    public Strings()
    {
    }

    public static ResourceManager ResourceManager => resourceMan ??= new ResourceManager("Nevolution.Core.Resources.Strings", typeof(Strings).Assembly);

    public static CultureInfo? Culture
    {
        get => resourceCulture;
        set => resourceCulture = value;
    }

    public static string Folder_Archive => ResourceManager.GetString(nameof(Folder_Archive), resourceCulture) ?? nameof(Folder_Archive);
    public static string Folder_Drafts => ResourceManager.GetString(nameof(Folder_Drafts), resourceCulture) ?? nameof(Folder_Drafts);
    public static string Folder_Inbox => ResourceManager.GetString(nameof(Folder_Inbox), resourceCulture) ?? nameof(Folder_Inbox);
    public static string Folder_Sent => ResourceManager.GetString(nameof(Folder_Sent), resourceCulture) ?? nameof(Folder_Sent);
    public static string Folder_Trash => ResourceManager.GetString(nameof(Folder_Trash), resourceCulture) ?? nameof(Folder_Trash);
    public static string AccountDialog_Cancel => ResourceManager.GetString(nameof(AccountDialog_Cancel), resourceCulture) ?? nameof(AccountDialog_Cancel);
    public static string AccountDialog_DisplayName => ResourceManager.GetString(nameof(AccountDialog_DisplayName), resourceCulture) ?? nameof(AccountDialog_DisplayName);
    public static string AccountDialog_Email => ResourceManager.GetString(nameof(AccountDialog_Email), resourceCulture) ?? nameof(AccountDialog_Email);
    public static string AccountDialog_ErrorDisplayNameRequired => ResourceManager.GetString(nameof(AccountDialog_ErrorDisplayNameRequired), resourceCulture) ?? nameof(AccountDialog_ErrorDisplayNameRequired);
    public static string AccountDialog_ErrorDuplicateEmail => ResourceManager.GetString(nameof(AccountDialog_ErrorDuplicateEmail), resourceCulture) ?? nameof(AccountDialog_ErrorDuplicateEmail);
    public static string AccountDialog_ErrorEmailRequired => ResourceManager.GetString(nameof(AccountDialog_ErrorEmailRequired), resourceCulture) ?? nameof(AccountDialog_ErrorEmailRequired);
    public static string AccountDialog_ErrorImapHostRequired => ResourceManager.GetString(nameof(AccountDialog_ErrorImapHostRequired), resourceCulture) ?? nameof(AccountDialog_ErrorImapHostRequired);
    public static string AccountDialog_ErrorImapPortInvalid => ResourceManager.GetString(nameof(AccountDialog_ErrorImapPortInvalid), resourceCulture) ?? nameof(AccountDialog_ErrorImapPortInvalid);
    public static string AccountDialog_ErrorPasswordRequired => ResourceManager.GetString(nameof(AccountDialog_ErrorPasswordRequired), resourceCulture) ?? nameof(AccountDialog_ErrorPasswordRequired);
    public static string AccountDialog_ErrorSaveFailed => ResourceManager.GetString(nameof(AccountDialog_ErrorSaveFailed), resourceCulture) ?? nameof(AccountDialog_ErrorSaveFailed);
    public static string AccountDialog_ErrorUsernameRequired => ResourceManager.GetString(nameof(AccountDialog_ErrorUsernameRequired), resourceCulture) ?? nameof(AccountDialog_ErrorUsernameRequired);
    public static string AccountDialog_Hint => ResourceManager.GetString(nameof(AccountDialog_Hint), resourceCulture) ?? nameof(AccountDialog_Hint);
    public static string AccountDialog_ImapHost => ResourceManager.GetString(nameof(AccountDialog_ImapHost), resourceCulture) ?? nameof(AccountDialog_ImapHost);
    public static string AccountDialog_ImapPort => ResourceManager.GetString(nameof(AccountDialog_ImapPort), resourceCulture) ?? nameof(AccountDialog_ImapPort);
    public static string AccountDialog_Password => ResourceManager.GetString(nameof(AccountDialog_Password), resourceCulture) ?? nameof(AccountDialog_Password);
    public static string AccountDialog_Save => ResourceManager.GetString(nameof(AccountDialog_Save), resourceCulture) ?? nameof(AccountDialog_Save);
    public static string AccountDialog_Title => ResourceManager.GetString(nameof(AccountDialog_Title), resourceCulture) ?? nameof(AccountDialog_Title);
    public static string AccountDialog_UseAsActive => ResourceManager.GetString(nameof(AccountDialog_UseAsActive), resourceCulture) ?? nameof(AccountDialog_UseAsActive);
    public static string AccountDialog_Username => ResourceManager.GetString(nameof(AccountDialog_Username), resourceCulture) ?? nameof(AccountDialog_Username);
    public static string Cli_AccountNotFound => ResourceManager.GetString(nameof(Cli_AccountNotFound), resourceCulture) ?? nameof(Cli_AccountNotFound);
    public static string Cli_AccountSaved => ResourceManager.GetString(nameof(Cli_AccountSaved), resourceCulture) ?? nameof(Cli_AccountSaved);
    public static string Cli_ActiveAccount => ResourceManager.GetString(nameof(Cli_ActiveAccount), resourceCulture) ?? nameof(Cli_ActiveAccount);
    public static string Cli_AuthenticationFailed => ResourceManager.GetString(nameof(Cli_AuthenticationFailed), resourceCulture) ?? nameof(Cli_AuthenticationFailed);
    public static string Cli_ConnectionFailed => ResourceManager.GetString(nameof(Cli_ConnectionFailed), resourceCulture) ?? nameof(Cli_ConnectionFailed);
    public static string Cli_DetailPrefix => ResourceManager.GetString(nameof(Cli_DetailPrefix), resourceCulture) ?? nameof(Cli_DetailPrefix);
    public static string Cli_ErrorPrefix => ResourceManager.GetString(nameof(Cli_ErrorPrefix), resourceCulture) ?? nameof(Cli_ErrorPrefix);
    public static string Cli_HostResolutionFailed => ResourceManager.GetString(nameof(Cli_HostResolutionFailed), resourceCulture) ?? nameof(Cli_HostResolutionFailed);
    public static string Cli_NoAccountsConfigured => ResourceManager.GetString(nameof(Cli_NoAccountsConfigured), resourceCulture) ?? nameof(Cli_NoAccountsConfigured);
    public static string Cli_NoActiveAccount => ResourceManager.GetString(nameof(Cli_NoActiveAccount), resourceCulture) ?? nameof(Cli_NoActiveAccount);
    public static string Cli_RequiredArgumentMissing => ResourceManager.GetString(nameof(Cli_RequiredArgumentMissing), resourceCulture) ?? nameof(Cli_RequiredArgumentMissing);
    public static string Cli_ResolvingHost => ResourceManager.GetString(nameof(Cli_ResolvingHost), resourceCulture) ?? nameof(Cli_ResolvingHost);
    public static string Cli_SyncedEmailsCount => ResourceManager.GetString(nameof(Cli_SyncedEmailsCount), resourceCulture) ?? nameof(Cli_SyncedEmailsCount);
    public static string Cli_SyncingFolder => ResourceManager.GetString(nameof(Cli_SyncingFolder), resourceCulture) ?? nameof(Cli_SyncingFolder);
    public static string Cli_UnknownAccountCommand => ResourceManager.GetString(nameof(Cli_UnknownAccountCommand), resourceCulture) ?? nameof(Cli_UnknownAccountCommand);
    public static string Cli_UsageAccountAdd => ResourceManager.GetString(nameof(Cli_UsageAccountAdd), resourceCulture) ?? nameof(Cli_UsageAccountAdd);
    public static string Cli_UsageAccountList => ResourceManager.GetString(nameof(Cli_UsageAccountList), resourceCulture) ?? nameof(Cli_UsageAccountList);
    public static string Cli_UsageAccountUse => ResourceManager.GetString(nameof(Cli_UsageAccountUse), resourceCulture) ?? nameof(Cli_UsageAccountUse);
    public static string Cli_UsageHeader => ResourceManager.GetString(nameof(Cli_UsageHeader), resourceCulture) ?? nameof(Cli_UsageHeader);
    public static string Language_English => ResourceManager.GetString(nameof(Language_English), resourceCulture) ?? nameof(Language_English);
    public static string Language_Spanish => ResourceManager.GetString(nameof(Language_Spanish), resourceCulture) ?? nameof(Language_Spanish);
    public static string MainWindow_FilterPlaceholder => ResourceManager.GetString(nameof(MainWindow_FilterPlaceholder), resourceCulture) ?? nameof(MainWindow_FilterPlaceholder);
    public static string MainWindow_HtmlFallbackNotice => ResourceManager.GetString(nameof(MainWindow_HtmlFallbackNotice), resourceCulture) ?? nameof(MainWindow_HtmlFallbackNotice);
    public static string MainWindow_LanguageLabel => ResourceManager.GetString(nameof(MainWindow_LanguageLabel), resourceCulture) ?? nameof(MainWindow_LanguageLabel);
    public static string MainWindow_LoadMore => ResourceManager.GetString(nameof(MainWindow_LoadMore), resourceCulture) ?? nameof(MainWindow_LoadMore);
    public static string MainWindow_ShowUnreadOnly => ResourceManager.GetString(nameof(MainWindow_ShowUnreadOnly), resourceCulture) ?? nameof(MainWindow_ShowUnreadOnly);
    public static string MainWindow_Title => ResourceManager.GetString(nameof(MainWindow_Title), resourceCulture) ?? nameof(MainWindow_Title);
    public static string MailBody_Loading => ResourceManager.GetString(nameof(MailBody_Loading), resourceCulture) ?? nameof(MailBody_Loading);
    public static string Menu_About => ResourceManager.GetString(nameof(Menu_About), resourceCulture) ?? nameof(Menu_About);
    public static string Menu_Account => ResourceManager.GetString(nameof(Menu_Account), resourceCulture) ?? nameof(Menu_Account);
    public static string Menu_AddAccount => ResourceManager.GetString(nameof(Menu_AddAccount), resourceCulture) ?? nameof(Menu_AddAccount);
    public static string Menu_Close => ResourceManager.GetString(nameof(Menu_Close), resourceCulture) ?? nameof(Menu_Close);
    public static string Menu_File => ResourceManager.GetString(nameof(Menu_File), resourceCulture) ?? nameof(Menu_File);
    public static string Menu_Help => ResourceManager.GetString(nameof(Menu_Help), resourceCulture) ?? nameof(Menu_Help);
    public static string Menu_SwitchAccount => ResourceManager.GetString(nameof(Menu_SwitchAccount), resourceCulture) ?? nameof(Menu_SwitchAccount);
    public static string Menu_View => ResourceManager.GetString(nameof(Menu_View), resourceCulture) ?? nameof(Menu_View);
    public static string Menu_ViewRefresh => ResourceManager.GetString(nameof(Menu_ViewRefresh), resourceCulture) ?? nameof(Menu_ViewRefresh);
    public static string Status_BackgroundDownloadStopped => ResourceManager.GetString(nameof(Status_BackgroundDownloadStopped), resourceCulture) ?? nameof(Status_BackgroundDownloadStopped);
    public static string Status_CannotDownloadSelectedMailBody => ResourceManager.GetString(nameof(Status_CannotDownloadSelectedMailBody), resourceCulture) ?? nameof(Status_CannotDownloadSelectedMailBody);
    public static string Status_CannotLoadActiveAccount => ResourceManager.GetString(nameof(Status_CannotLoadActiveAccount), resourceCulture) ?? nameof(Status_CannotLoadActiveAccount);
    public static string Status_CannotSyncActiveFolder => ResourceManager.GetString(nameof(Status_CannotSyncActiveFolder), resourceCulture) ?? nameof(Status_CannotSyncActiveFolder);
    public static string Status_InitialLoadFailed => ResourceManager.GetString(nameof(Status_InitialLoadFailed), resourceCulture) ?? nameof(Status_InitialLoadFailed);
    public static string Status_InitialLoadFailedImap => ResourceManager.GetString(nameof(Status_InitialLoadFailedImap), resourceCulture) ?? nameof(Status_InitialLoadFailedImap);
    public static string Status_LoadingLocalEmails => ResourceManager.GetString(nameof(Status_LoadingLocalEmails), resourceCulture) ?? nameof(Status_LoadingLocalEmails);
    public static string Status_NoLocalEmailsYet => ResourceManager.GetString(nameof(Status_NoLocalEmailsYet), resourceCulture) ?? nameof(Status_NoLocalEmailsYet);
    public static string Status_NoActiveAccount => ResourceManager.GetString(nameof(Status_NoActiveAccount), resourceCulture) ?? nameof(Status_NoActiveAccount);
    public static string Status_SyncingFolder => ResourceManager.GetString(nameof(Status_SyncingFolder), resourceCulture) ?? nameof(Status_SyncingFolder);
    public static string UserError_ImapAuthentication => ResourceManager.GetString(nameof(UserError_ImapAuthentication), resourceCulture) ?? nameof(UserError_ImapAuthentication);
    public static string UserError_ImapConnection => ResourceManager.GetString(nameof(UserError_ImapConnection), resourceCulture) ?? nameof(UserError_ImapConnection);
    public static string UserError_ImapGeneric => ResourceManager.GetString(nameof(UserError_ImapGeneric), resourceCulture) ?? nameof(UserError_ImapGeneric);
    public static string UserError_ImapHostResolution => ResourceManager.GetString(nameof(UserError_ImapHostResolution), resourceCulture) ?? nameof(UserError_ImapHostResolution);
    public static string UserError_ImapInvalidAccountConfiguration => ResourceManager.GetString(nameof(UserError_ImapInvalidAccountConfiguration), resourceCulture) ?? nameof(UserError_ImapInvalidAccountConfiguration);
    public static string UserError_ImapSecurity => ResourceManager.GetString(nameof(UserError_ImapSecurity), resourceCulture) ?? nameof(UserError_ImapSecurity);
}
